uint64 timestamp	# time since system start (microseconds)

float32 current_lat       # current latitude
float32 current_lon       # current longitude
float32 track_angle
float32 true_air_speed
float32 pre_pos_sp_lat       # previous waypoint latitude
float32 pre_pos_sp_lon       # previous waypoint longitude
float32 cur_sp_type          # 1:Line;0:curved
float32 abs_cur_radium
float32 cur_center_lat
float32 cur_center_lon
float32 cur_pos_sp_lat
float32 cur_pos_sp_lon
float32 roll_body
